# Generated by Django 3.2.5 on 2021-08-09 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Employee',
        ),
    ]
